# Generated by Django 5.2.7 on 2025-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_employee_alter_item_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
